const ROLES = {
  ADMIN: 'ADMIN',
  MEDICAL_REP: 'MEDICAL_REP'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
  DELIVERED: 'DELIVERED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED'
};

const LEDGER_TYPE = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT'
};

const LEDGER_ENTITY_TYPE = {
  PHARMACY: 'PHARMACY'
};

const LEDGER_REFERENCE_TYPE = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  RETURN: 'RETURN'
};

const TRANSACTION_TYPE = {
  SALE: 'SALE',
  RETURN: 'RETURN',
  EXPENSE: 'EXPENSE'
};

const PAYMENT_METHOD = {
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  BANK_TRANSFER: 'BANK_TRANSFER',
  UPI: 'UPI'
};

const EXPENSE_CATEGORY = {
  DOCTOR_INVESTMENT: 'DOCTOR_INVESTMENT',
  SALARY: 'SALARY',
  RENT: 'RENT',
  LOGISTICS: 'LOGISTICS',
  OFFICE: 'OFFICE',
  OTHER: 'OTHER'
};

const PAYROLL_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID'
};

const WEEKLY_PLAN_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  REVIEWED: 'REVIEWED'
};

module.exports = {
  ROLES,
  ORDER_STATUS,
  LEDGER_TYPE,
  LEDGER_ENTITY_TYPE,
  LEDGER_REFERENCE_TYPE,
  TRANSACTION_TYPE,
  PAYMENT_METHOD,
  EXPENSE_CATEGORY,
  PAYROLL_STATUS,
  WEEKLY_PLAN_STATUS
};
